// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendShortcut() {
  return window['go']['main']['App']['AppendShortcut']();
}

export function CheckShortcuts() {
  return window['go']['main']['App']['CheckShortcuts']();
}

export function ReadJson(arg1) {
  return window['go']['main']['App']['ReadJson'](arg1);
}

export function ToggleShortcut(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleShortcut'](arg1, arg2, arg3);
}
