// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadJson() {
  return window['go']['main']['App']['ReadJson']();
}

export function ToggleShortcut(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleShortcut'](arg1, arg2, arg3);
}
