// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ReadJson():Promise<Array<main.Shortcut>>;

export function ToggleShortcut(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;
