// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendShortcut():Promise<void>;

export function CheckShortcuts():Promise<Array<main.Shortcut>>;

export function ReadJson(arg1:string):Promise<Array<main.Shortcut>>;

export function RemoveByID(arg1:number):Promise<Array<main.Shortcut>>;

export function ToggleShortcut(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;
